// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIJSmthrtlXiXU9Q6oCZPtLeAJaC8P2B0',
    appId: '1:645550125422:web:1835e59f9402695322517f',
    messagingSenderId: '645550125422',
    projectId: 'super-duper-bassoon-b7b6e',
    authDomain: 'super-duper-bassoon-b7b6e.firebaseapp.com',
    storageBucket: 'super-duper-bassoon-b7b6e.appspot.com',
    measurementId: 'G-0GY1MRFR5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn_VXy0IiWDnk33bnN-e5NaV-v81rx2I8',
    appId: '1:645550125422:android:f653a3fa7edecc3c22517f',
    messagingSenderId: '645550125422',
    projectId: 'super-duper-bassoon-b7b6e',
    storageBucket: 'super-duper-bassoon-b7b6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtkYX12EI1YfAzDxItWepOvbtZHHDxz_8',
    appId: '1:645550125422:ios:94a69fa8b93ba1f322517f',
    messagingSenderId: '645550125422',
    projectId: 'super-duper-bassoon-b7b6e',
    storageBucket: 'super-duper-bassoon-b7b6e.appspot.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtkYX12EI1YfAzDxItWepOvbtZHHDxz_8',
    appId: '1:645550125422:ios:83f2d6a9417234c222517f',
    messagingSenderId: '645550125422',
    projectId: 'super-duper-bassoon-b7b6e',
    storageBucket: 'super-duper-bassoon-b7b6e.appspot.com',
    iosBundleId: 'com.example.flutterToDoList.RunnerTests',
  );
}
